name: Build and Dockerize Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del código
    - name: Check out the code
      uses: actions/checkout@v2

    # Paso 2: Configurar JDK 17 (usando Adoptium/Temurin)
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'  # Usando Adoptium Temurin
        java-version: '17'       # Especificamos la versión de Java 17

    # Paso 3: Construir el proyecto con Maven
    - name: Build with Maven
      run: mvn clean package -DskipTests

    # Paso 4: Construir la imagen Docker
    - name: Build Docker image
      run: docker build -t prueba2-app .

    # Paso 5: Ejecutar el contenedor Docker
    - name: Run Docker container
      run: docker run -d -p 8080:8080 --name prueba2 prueba2-app

    # Paso 6: Verificar que el contenedor está corriendo
    - name: Verify Docker container is running
      run: docker ps

    # Paso 7: Verificar si la aplicación está funcionando (con curl)
    - name: Verify app is running
      run: curl http://localhost:8080
