name: Build and Test Spring Boot App in Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Spring Boot App
      run: ./mvnw clean package -DskipTests

    - name: Build Docker image
      run: docker build -t calculadora-api .

    - name: Run Docker container
      run: docker run -d -p 8080:8080 --name calculadora-api-container calculadora-api

    - name: Esperar a que la app esté lista
      run: |
        for i in {1..15}; do
          echo "Esperando... intento $i"
          sleep 3
          if curl -s http://localhost:8080/ > /dev/null; then
            echo "✅ Aplicación disponible"
            exit 0
          fi
        done
        echo "❌ La aplicación no respondió a tiempo"
        docker logs calculadora-api-container
        exit 1

    - name: Test calculadora endpoint
      run: |
        echo "Probando endpoint /api/calculadora/sumar?a=5&b=7"
        curl -v "http://localhost:8080/api/calculadora/sumar?a=5&b=7"
