name: Build and Dockerize Spring Boot App

on:
  push:
    branches:
      - main  # Se ejecuta cuando haces un push a la rama 'main'
  pull_request:
    branches:
      - main  # Se ejecuta para pull requests hacia la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Usamos un runner de Ubuntu

    steps:
    # 1. Checkout del repositorio
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Configurar Java (usamos OpenJDK 17)
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'

    # 3. Instalar Maven (si no está ya en el runner)
    - name: Install Maven
      run: sudo apt-get install maven -y

    # 4. Compilar el proyecto con Maven (clean package)
    - name: Build with Maven
      run: mvn clean package --file pom.xml

    # 5. Construir la imagen Docker
    - name: Build Docker image
      run: |
        docker build -t prueba2-app .

    # 6. Iniciar el contenedor Docker (Opcional: solo para verificar)
    - name: Run Docker container
      run: |
        docker run -d -p 8080:8080 --name prueba2 prueba2-app

    # 7. Verificar que el contenedor esté corriendo
    - name: Verify Docker container is running
      run: docker ps
