name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t spring-app .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 --name app spring-app

      - name: Esperar a que la app esté disponible
        run: |
          for i in {1..15}; do
            if curl -s http://localhost:8080; then
              echo "App disponible ✅"
              exit 0
            else
              echo "Esperando... intento $i"
              sleep 5
            fi
          done
          echo "La aplicación no respondió a tiempo ❌"
          docker logs app
          exit 1
